### ISSUE TITLE
Rename repo/binary + add contract call support

### ISSUE THREAD

**Issue by rdf004** [InjectiveLabs/etherman#1]
evm-deploy-contract implies that each command sent is related to a deployment, yet one can use the tx command to send transactions. It woud be more accurate to change the name to evm-contract to reduce the potential for confusion. 

Also, it would also be useful to support contract calls as well.

**Comment by xlab** [comment]
@rdf004 good point, I had plans to rename it as soon as we reach `v1.0.0` state. I think it's very close now to that state, so I'm going to rename repo now.

Frankly, I didn't see this issue before, I decided to rename the repo on my own, and before doing so just wanted to check issues to get the idea if anyone else uses that yet. Seems not :)

P.S. the tool evolved so much, not only contract calls, but also logs, and also coverage ;)
